@extends('layouts.dashboard')

@section('title', 'Agendar Cita - Fecha y Hora')

@push('styles')
<link rel="stylesheet" href="{{ asset('assets/css/appointments.css') }}">
@endpush

@section('content')
<section class="booking-container">
    <!-- Back Navigation -->
    <div class="back-nav">
        <a href="{{ route('dashboard') }}" class="btn-back-link">
            <i class="fas fa-arrow-left"></i> Regresar al Panel
        </a>
    </div>

    <!-- Stepper -->
    <div class="stepper">
        <div class="step active"><span>1</span><p>Fecha</p></div>
        <div class="step"><span>2</span><p>Archivos</p></div>
        <div class="step"><span>3</span><p>Salud</p></div>
        <div class="step"><span>4</span><p>Confirma</p></div>
        <div class="step"><span>5</span><p>Pago</p></div>
    </div>

    @if(session('error'))
        <div class="alert alert-danger" style="background: #f8d7da; color: #721c24; padding: 1rem; border-radius: 8px; margin-bottom: 1.5rem;">
            {{ session('error') }}
        </div>
    @endif

    <form action="{{ route('appointments.step1.process') }}" method="POST" id="step1Form">
        @csrf
        <input type="hidden" name="appointment_date" id="selectedDate" value="{{ old('appointment_date', session('appointment.date')) }}">
        <input type="hidden" name="appointment_time" id="selectedTime" value="{{ old('appointment_time', session('appointment.time')) }}">
        <input type="hidden" name="timezone" id="selectedTimezone" value="America/Mexico_City">

        <div class="booking-grid">
            <!-- Calendar Section -->
            <div class="calendar-section">
                <div class="calendar-header">
                    <button type="button" class="nav-cal-btn" id="prevWeek"><i class="fas fa-chevron-left"></i></button>
                    <h3 id="weekDisplay">Semana del 29 de Dic - 04 de Ene</h3>
                    <button type="button" class="nav-cal-btn" id="nextWeek"><i class="fas fa-chevron-right"></i></button>
                </div>

                <div class="slots-container" id="slotsContainer">
                    <!-- Slots will be generated by JavaScript -->
                </div>
            </div>

            <!-- Sidebar -->
            <aside class="booking-sidebar">
                <div class="helper-card">
                    <h4><i class="fas fa-info-circle"></i> Ayuda para agendar</h4>
                    <ul class="aid-list">
                        <li><strong>Seleccione una fecha y hora:</strong> Use las flechas para navegar entre semanas.</li>
                        <li><strong>Cuadros verdes:</strong> Indican espacios disponibles. Haga clic para reservar.</li>
                        <li><strong>Zonas horarias:</strong> Todos los horarios se muestran segun su zona horaria detectada: <br>
                            <span class="tz-highlight">Zona Centro / Ciudad de Mexico</span>
                        </li>
                    </ul>
                </div>

                <div class="summary-card">
                    <h4>Resumen de Cita</h4>
                    <p class="empty-msg" id="summaryContent">Seleccione un espacio disponible para continuar.</p>
                    <button type="submit" class="btn-next" id="btnNext" disabled>
                        Siguiente Paso <i class="fas fa-arrow-right"></i>
                    </button>
                </div>

                <!-- Timezone Selection -->
                <div class="timezone-card">
                    <label><i class="fas fa-globe"></i> Zona Horaria</label>
                    <select name="timezone_select" id="timezoneSelect" class="timezone-select">
                        <option value="America/Mexico_City">Zona Central / Ciudad de Mexico (GMT-6)</option>
                        <option value="America/Tijuana">Zona Pacifico / Tijuana (GMT-8)</option>
                        <option value="America/Cancun">Zona Sureste / Cancun (GMT-5)</option>
                        <option value="UTC">Tiempo Universal Coordinado (UTC)</option>
                    </select>
                </div>
            </aside>
        </div>
    </form>
</section>
@endsection

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    const availableSlots = @json($availableSlots);
    let currentWeekStart = new Date();
    let selectedDate = null;
    let selectedTime = null;

    // Set to Monday of current week
    const dayOfWeek = currentWeekStart.getDay();
    const diff = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
    currentWeekStart.setDate(currentWeekStart.getDate() + diff);
    currentWeekStart.setHours(0, 0, 0, 0);

    const slotsContainer = document.getElementById('slotsContainer');
    const weekDisplay = document.getElementById('weekDisplay');
    const selectedDateInput = document.getElementById('selectedDate');
    const selectedTimeInput = document.getElementById('selectedTime');
    const summaryContent = document.getElementById('summaryContent');
    const btnNext = document.getElementById('btnNext');

    const monthNames = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'];
    const dayNames = ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'];
    const fullDayNames = ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'];

    function formatDateForDisplay(date) {
        return date.getDate() + ' de ' + monthNames[date.getMonth()];
    }

    function formatDateString(date) {
        return date.toISOString().split('T')[0];
    }

    function renderWeek() {
        const weekEnd = new Date(currentWeekStart);
        weekEnd.setDate(weekEnd.getDate() + 4); // Monday to Friday (5 days)

        weekDisplay.textContent = `Semana del ${formatDateForDisplay(currentWeekStart)} - ${formatDateForDisplay(weekEnd)}`;

        const today = new Date();
        today.setHours(0, 0, 0, 0);

        let html = '';

        // Generate 5 columns (Monday to Friday)
        for (let i = 0; i < 5; i++) {
            const date = new Date(currentWeekStart);
            date.setDate(date.getDate() + i);
            const dateStr = formatDateString(date);
            const dayName = dayNames[date.getDay()];
            const dayNum = date.getDate();
            const isPast = date < today;

            html += `<div class="day-column">`;
            html += `<span class="day-name">${dayName} ${dayNum}</span>`;

            // Time slots from 09:00 to 17:00
            const times = ['09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00'];

            times.forEach(time => {
                const slotData = availableSlots[dateStr];
                let isAvailable = false;

                if (slotData && slotData.slots) {
                    const slot = slotData.slots.find(s => s.time === time);
                    isAvailable = slot && slot.available && !isPast;
                }

                const isSelected = selectedDate === dateStr && selectedTime === time;

                if (isPast || !isAvailable) {
                    html += `<button type="button" class="slot taken" disabled>${time}</button>`;
                } else {
                    html += `<button type="button" class="slot available ${isSelected ? 'selected' : ''}" data-date="${dateStr}" data-time="${time}">${time}</button>`;
                }
            });

            html += `</div>`;
        }

        slotsContainer.innerHTML = html;

        // Add click handlers
        document.querySelectorAll('.slot.available').forEach(slot => {
            slot.addEventListener('click', function() {
                selectSlot(this.dataset.date, this.dataset.time, this);
            });
        });
    }

    function selectSlot(date, time, element) {
        // Remove previous selection
        document.querySelectorAll('.slot').forEach(s => s.classList.remove('selected'));

        // Add selection to clicked slot
        element.classList.add('selected');

        selectedDate = date;
        selectedTime = time;
        selectedDateInput.value = date;
        selectedTimeInput.value = time;

        // Parse date for display
        const dateObj = new Date(date + 'T12:00:00');
        const dayName = fullDayNames[dateObj.getDay()];
        const dayNum = dateObj.getDate();
        const monthName = monthNames[dateObj.getMonth()];

        // Update summary
        summaryContent.innerHTML = `
            <div class="selected-slot-summary">
                <p style="margin:0; color:#11507a; font-weight:bold;">Cita seleccionada:</p>
                <p style="margin:5px 0 0 0; color:#555;">${dayName} ${dayNum} de ${monthName} a las ${time} hrs.</p>
            </div>
        `;

        // Enable next button
        btnNext.disabled = false;

        // Scroll to button on mobile
        if (window.innerWidth < 768) {
            btnNext.scrollIntoView({ behavior: 'smooth' });
        }
    }

    // Navigation
    document.getElementById('prevWeek').addEventListener('click', function() {
        currentWeekStart.setDate(currentWeekStart.getDate() - 7);
        renderWeek();
    });

    document.getElementById('nextWeek').addEventListener('click', function() {
        currentWeekStart.setDate(currentWeekStart.getDate() + 7);
        renderWeek();
    });

    // Timezone selection
    document.getElementById('timezoneSelect').addEventListener('change', function() {
        document.getElementById('selectedTimezone').value = this.value;
    });

    // Initialize
    renderWeek();

    // Restore previous selection if exists
    const prevDate = '{{ session("appointment.date") }}';
    const prevTime = '{{ session("appointment.time") }}';
    if (prevDate && prevTime) {
        selectedDate = prevDate;
        selectedTime = prevTime;
        selectedDateInput.value = prevDate;
        selectedTimeInput.value = prevTime;

        // Check if the date is in current week view
        const prevDateObj = new Date(prevDate);
        if (prevDateObj >= currentWeekStart) {
            const slot = document.querySelector(`.slot[data-date="${prevDate}"][data-time="${prevTime}"]`);
            if (slot) {
                selectSlot(prevDate, prevTime, slot);
            }
        }
    }
});
</script>
@endpush
