@extends('layouts.dashboard')

@section('title', 'Agendar Cita - Fecha y Hora')

@push('styles')
<link rel="stylesheet" href="{{ asset('assets/css/appointments.css') }}">
@endpush

@section('content')
<section class="appointment-dashboard">
    <!-- Stepper -->
    <div class="stepper">
        <div class="step active">
            <div class="step-number">1</div>
            <span class="step-label">Fecha y Hora</span>
        </div>
        <div class="step">
            <div class="step-number">2</div>
            <span class="step-label">Archivos</span>
        </div>
        <div class="step">
            <div class="step-number">3</div>
            <span class="step-label">Declaracion</span>
        </div>
        <div class="step">
            <div class="step-number">4</div>
            <span class="step-label">Confirmacion</span>
        </div>
        <div class="step">
            <div class="step-number">5</div>
            <span class="step-label">Pago</span>
        </div>
    </div>

    <!-- Main Content -->
    <div class="appointment-container">
        <div class="appointment-header">
            <h2><i class="fas fa-calendar-alt"></i> Seleccione Fecha y Hora</h2>
            <p>Elija el dia y horario que mejor se adapte a su disponibilidad para realizar su consulta medica virtual.</p>
        </div>

        @if(session('error'))
            <div class="alert alert-danger" style="background: #f8d7da; color: #721c24; padding: 1rem; border-radius: 8px; margin-bottom: 1.5rem;">
                {{ session('error') }}
            </div>
        @endif

        <form action="{{ route('appointments.step1.process') }}" method="POST" id="step1Form">
            @csrf
            <input type="hidden" name="appointment_date" id="selectedDate" value="{{ old('appointment_date', session('appointment.date')) }}">
            <input type="hidden" name="appointment_time" id="selectedTime" value="{{ old('appointment_time', session('appointment.time')) }}">
            <input type="hidden" name="timezone" id="selectedTimezone" value="America/Mexico_City">

            <div class="calendar-container">
                <!-- Calendar -->
                <div class="calendar-wrapper">
                    <div class="calendar-header">
                        <button type="button" class="calendar-nav-btn" id="prevMonth"><i class="fas fa-chevron-left"></i></button>
                        <h3 id="currentMonth">Enero 2026</h3>
                        <button type="button" class="calendar-nav-btn" id="nextMonth"><i class="fas fa-chevron-right"></i></button>
                    </div>
                    <div class="calendar-days">
                        <span>Dom</span>
                        <span>Lun</span>
                        <span>Mar</span>
                        <span>Mie</span>
                        <span>Jue</span>
                        <span>Vie</span>
                        <span>Sab</span>
                    </div>
                    <div class="calendar-dates" id="calendarDates">
                        <!-- Calendar dates will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Time Slots -->
                <div class="time-slots-panel">
                    <h4><i class="fas fa-clock"></i> Horarios Disponibles</h4>
                    <p id="selectedDateDisplay" style="color: #666; font-size: 0.9rem; margin-bottom: 1rem;">
                        Seleccione una fecha para ver los horarios disponibles
                    </p>
                    <div class="time-slots-grid" id="timeSlotsGrid">
                        <!-- Time slots will be generated when a date is selected -->
                    </div>
                </div>
            </div>

            <!-- Timezone Selection -->
            <div class="form-group" style="margin-top: 1.5rem;">
                <label><i class="fas fa-globe"></i> Zona Horaria</label>
                <select name="timezone" id="timezoneSelect" class="form-control" style="padding: 0.75rem; border: 2px solid #e0e0e0; border-radius: 8px; width: 100%;">
                    <option value="America/Mexico_City">Zona Central / Ciudad de Mexico (GMT-6)</option>
                    <option value="America/Tijuana">Zona Pacifico / Tijuana (GMT-8)</option>
                    <option value="America/Cancun">Zona Sureste / Cancun (GMT-5)</option>
                    <option value="UTC">Tiempo Universal Coordinado (UTC)</option>
                </select>
            </div>

            <!-- Navigation -->
            <div class="step-navigation">
                <a href="{{ route('dashboard') }}" class="btn-back">
                    <i class="fas fa-arrow-left"></i> Cancelar
                </a>
                <button type="submit" class="btn-next" id="btnNext" disabled>
                    Siguiente <i class="fas fa-arrow-right"></i>
                </button>
            </div>
        </form>
    </div>
</section>
@endsection

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    const availableSlots = @json($availableSlots);
    let currentDate = new Date();
    let selectedDate = null;
    let selectedTime = null;

    const calendarDates = document.getElementById('calendarDates');
    const currentMonthEl = document.getElementById('currentMonth');
    const timeSlotsGrid = document.getElementById('timeSlotsGrid');
    const selectedDateDisplay = document.getElementById('selectedDateDisplay');
    const selectedDateInput = document.getElementById('selectedDate');
    const selectedTimeInput = document.getElementById('selectedTime');
    const btnNext = document.getElementById('btnNext');

    const monthNames = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                        'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];
    const dayNames = ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'];

    function renderCalendar() {
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();

        currentMonthEl.textContent = `${monthNames[month]} ${year}`;

        const firstDay = new Date(year, month, 1).getDay();
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        let html = '';

        // Empty cells for days before the first day of the month
        for (let i = 0; i < firstDay; i++) {
            html += '<div class="calendar-date empty"></div>';
        }

        // Days of the month
        for (let day = 1; day <= daysInMonth; day++) {
            const date = new Date(year, month, day);
            const dateStr = date.toISOString().split('T')[0];
            const isPast = date < today;
            const isSunday = date.getDay() === 0;
            const isAvailable = availableSlots[dateStr] !== undefined;
            const isToday = date.getTime() === today.getTime();
            const isSelected = selectedDate === dateStr;

            let classes = 'calendar-date';
            if (isPast || isSunday || !isAvailable) classes += ' disabled';
            if (isToday) classes += ' today';
            if (isSelected) classes += ' selected';

            html += `<div class="${classes}" data-date="${dateStr}">${day}</div>`;
        }

        calendarDates.innerHTML = html;

        // Add click handlers
        document.querySelectorAll('.calendar-date:not(.disabled):not(.empty)').forEach(el => {
            el.addEventListener('click', function() {
                selectDate(this.dataset.date);
            });
        });
    }

    function selectDate(dateStr) {
        selectedDate = dateStr;
        selectedDateInput.value = dateStr;
        selectedTime = null;
        selectedTimeInput.value = '';

        // Update calendar UI
        document.querySelectorAll('.calendar-date').forEach(el => {
            el.classList.remove('selected');
        });
        document.querySelector(`.calendar-date[data-date="${dateStr}"]`).classList.add('selected');

        // Show time slots
        renderTimeSlots(dateStr);
        updateNextButton();
    }

    function renderTimeSlots(dateStr) {
        const dayData = availableSlots[dateStr];
        if (!dayData) {
            timeSlotsGrid.innerHTML = '<p>No hay horarios disponibles para esta fecha.</p>';
            return;
        }

        const date = new Date(dateStr + 'T12:00:00');
        selectedDateDisplay.textContent = `${dayNames[date.getDay()]}, ${date.getDate()} de ${monthNames[date.getMonth()]}`;

        let html = '';
        dayData.slots.forEach(slot => {
            const isSelected = selectedTime === slot.time;
            const classes = `time-slot ${isSelected ? 'selected' : ''} ${!slot.available ? 'disabled' : ''}`;
            html += `<div class="${classes}" data-time="${slot.time}">${slot.display}</div>`;
        });

        timeSlotsGrid.innerHTML = html;

        // Add click handlers
        document.querySelectorAll('.time-slot:not(.disabled)').forEach(el => {
            el.addEventListener('click', function() {
                selectTime(this.dataset.time);
            });
        });
    }

    function selectTime(time) {
        selectedTime = time;
        selectedTimeInput.value = time;

        // Update UI
        document.querySelectorAll('.time-slot').forEach(el => {
            el.classList.remove('selected');
        });
        document.querySelector(`.time-slot[data-time="${time}"]`).classList.add('selected');

        updateNextButton();
    }

    function updateNextButton() {
        btnNext.disabled = !(selectedDate && selectedTime);
    }

    // Navigation
    document.getElementById('prevMonth').addEventListener('click', function() {
        currentDate.setMonth(currentDate.getMonth() - 1);
        renderCalendar();
    });

    document.getElementById('nextMonth').addEventListener('click', function() {
        currentDate.setMonth(currentDate.getMonth() + 1);
        renderCalendar();
    });

    // Timezone selection
    document.getElementById('timezoneSelect').addEventListener('change', function() {
        document.getElementById('selectedTimezone').value = this.value;
    });

    // Initialize
    renderCalendar();

    // Restore previous selection if exists
    const prevDate = '{{ session("appointment.date") }}';
    const prevTime = '{{ session("appointment.time") }}';
    if (prevDate) {
        selectDate(prevDate);
        if (prevTime) {
            setTimeout(() => selectTime(prevTime), 100);
        }
    }
});
</script>
@endpush
